use core::{arch::global_asm, mem::offset_of};

use super::register::GuestRegisters;

unsafe extern "C" {
    pub unsafe fn asm_vmrun(vmcb_phys_addr: u64, registers: *mut GuestRegisters);
}

global_asm!(
    ".global asm_vmrun",
    ".type asm_vmrun, @function",
    "asm_vmrun:",
    "push rbp",
    "push r15",
    "push r14",
    "push r13",
    "push r12",
    "push rbx",
    "push rsi",
    "push rdi",
    "mov rax, rsi",
    "mov rcx, [rax + {rcx}]",
    "mov rdx, [rax + {rdx}]",
    "mov rbx, [rax + {rbx}]",
    "mov rbp, [rax + {rbp}]",
    "mov rsi, [rax + {rsi}]",
    "mov rdi, [rax + {rdi}]",
    "mov r8, [rax + {r8}]",
    "mov r9, [rax + {r9}]",
    "mov r10, [rax + {r10}]",
    "mov r11, [rax + {r11}]",
    "mov r12, [rax + {r12}]",
    "mov r13, [rax + {r13}]",
    "mov r14, [rax + {r14}]",
    "mov r15, [rax + {r15}]",
    "movaps xmm0, [rax + {xmm0}]",
    "movaps xmm1, [rax + {xmm1}]",
    "movaps xmm2, [rax + {xmm2}]",
    "movaps xmm3, [rax + {xmm3}]",
    "movaps xmm4, [rax + {xmm4}]",
    "movaps xmm5, [rax + {xmm5}]",
    "movaps xmm6, [rax + {xmm6}]",
    "movaps xmm7, [rax + {xmm7}]",
    "pop rax",
    "vmrun",
    "push rax",
    "mov rax, [rsp + 8]",
    "mov [rax + {rcx}], rcx",
    "mov [rax + {rdx}], rdx",
    "mov [rax + {rbx}], rbx",
    "mov [rax + {rbp}], rbp",
    "mov [rax + {rsi}], rsi",
    "mov [rax + {rdi}], rdi",
    "mov [rax + {r8}], r8",
    "mov [rax + {r9}], r9",
    "mov [rax + {r10}], r10",
    "mov [rax + {r11}], r11",
    "mov [rax + {r12}], r12",
    "mov [rax + {r13}], r13",
    "mov [rax + {r14}], r14",
    "mov [rax + {r15}], r15",
    "movaps [rax + {xmm0}], xmm0",
    "movaps [rax + {xmm1}], xmm1",
    "movaps [rax + {xmm2}], xmm2",
    "movaps [rax + {xmm3}], xmm3",
    "movaps [rax + {xmm4}], xmm4",
    "movaps [rax + {xmm5}], xmm5",
    "movaps [rax + {xmm6}], xmm6",
    "movaps [rax + {xmm7}], xmm7",
    "add rsp, 16",
    "pop rbx",
    "pop r12",
    "pop r13",
    "pop r14",
    "pop r15",
    "pop rbp",
    "ret",
    ".size asm_vmrun, . - asm_vmrun",
    rcx = const offset_of!(GuestRegisters, rcx),
    rdx = const offset_of!(GuestRegisters, rdx),
    rbx = const offset_of!(GuestRegisters, rbx),
    rbp = const offset_of!(GuestRegisters, rbp),
    rsi = const offset_of!(GuestRegisters, rsi),
    rdi = const offset_of!(GuestRegisters, rdi),
    r8 = const offset_of!(GuestRegisters, r8),
    r9 = const offset_of!(GuestRegisters, r9),
    r10 = const offset_of!(GuestRegisters, r10),
    r11 = const offset_of!(GuestRegisters, r11),
    r12 = const offset_of!(GuestRegisters, r12),
    r13 = const offset_of!(GuestRegisters, r13),
    r14 = const offset_of!(GuestRegisters, r14),
    r15 = const offset_of!(GuestRegisters, r15),
    xmm0 = const offset_of!(GuestRegisters, xmm0),
    xmm1 = const offset_of!(GuestRegisters, xmm1),
    xmm2 = const offset_of!(GuestRegisters, xmm2),
    xmm3 = const offset_of!(GuestRegisters, xmm3),
    xmm4 = const offset_of!(GuestRegisters, xmm4),
    xmm5 = const offset_of!(GuestRegisters, xmm5),
    xmm6 = const offset_of!(GuestRegisters, xmm6),
    xmm7 = const offset_of!(GuestRegisters, xmm7),
);
