use core::{arch::global_asm, mem::offset_of};

use super::register::GuestRegisters;
use crate::vmm::x86_64::common::fxsave::FxState;

unsafe extern "C" {
    pub unsafe fn asm_vmrun(
        vmcb_phys_addr: u64,
        registers: *mut GuestRegisters,
        host_fx_state: *mut FxState,
        guest_fx_state: *mut FxState,
        host_xsave_addr: u64,
        host_xsave_mask: u64,
    );
}

global_asm!(
    ".global asm_vmrun",
    ".type asm_vmrun, @function",
    "asm_vmrun:",
    "push rbp",
    "push r15",
    "push r14",
    "push r13",
    "push r12",
    "push rbx",
    "push rsi",
    "push rdi",
    "push rdx",
    "push rcx",
    "push r8",
    "push r9",
    "test r9, r9",
    "jnz 1f",
    "fxsave64 [rdx]",
    "1:",
    "fxrstor64 [rcx]",
    "mov rax, rsi",
    "mov rcx, [rax + {rcx}]",
    "mov rdx, [rax + {rdx}]",
    "mov rbx, [rax + {rbx}]",
    "mov rbp, [rax + {rbp}]",
    "mov rsi, [rax + {rsi}]",
    "mov rdi, [rax + {rdi}]",
    "mov r8, [rax + {r8}]",
    "mov r9, [rax + {r9}]",
    "mov r10, [rax + {r10}]",
    "mov r11, [rax + {r11}]",
    "mov r12, [rax + {r12}]",
    "mov r13, [rax + {r13}]",
    "mov r14, [rax + {r14}]",
    "mov r15, [rax + {r15}]",
    "mov rax, [rsp + 32]",
    "vmrun",
    "push rax",
    "mov rax, [rsp + 48]",
    "mov [rax + {rcx}], rcx",
    "mov [rax + {rdx}], rdx",
    "mov [rax + {rbx}], rbx",
    "mov [rax + {rbp}], rbp",
    "mov [rax + {rsi}], rsi",
    "mov [rax + {rdi}], rdi",
    "mov [rax + {r8}], r8",
    "mov [rax + {r9}], r9",
    "mov [rax + {r10}], r10",
    "mov [rax + {r11}], r11",
    "mov [rax + {r12}], r12",
    "mov [rax + {r13}], r13",
    "mov [rax + {r14}], r14",
    "mov [rax + {r15}], r15",
    "mov rax, [rsp + 24]",
    "fxsave64 [rax]",
    "mov rax, [rsp + 8]", // host XSAVE mask
    "test rax, rax",
    "jz 2f",
    "mov rdx, rax",
    "shr rdx, 32",
    "xor ecx, ecx",
    "xsetbv",
    "mov rax, [rsp + 8]",
    "mov rdx, rax",
    "shr rdx, 32",
    "mov rcx, [rsp + 16]", // host XSAVE address
    "xrstor64 [rcx]",
    "jmp 3f",
    "2:",
    "mov rax, [rsp + 32]", // host FXSAVE address
    "fxrstor64 [rax]",
    "3:",
    "add rsp, 56",
    "pop rbx",
    "pop r12",
    "pop r13",
    "pop r14",
    "pop r15",
    "pop rbp",
    "ret",
    ".size asm_vmrun, . - asm_vmrun",
    rcx = const offset_of!(GuestRegisters, rcx),
    rdx = const offset_of!(GuestRegisters, rdx),
    rbx = const offset_of!(GuestRegisters, rbx),
    rbp = const offset_of!(GuestRegisters, rbp),
    rsi = const offset_of!(GuestRegisters, rsi),
    rdi = const offset_of!(GuestRegisters, rdi),
    r8 = const offset_of!(GuestRegisters, r8),
    r9 = const offset_of!(GuestRegisters, r9),
    r10 = const offset_of!(GuestRegisters, r10),
    r11 = const offset_of!(GuestRegisters, r11),
    r12 = const offset_of!(GuestRegisters, r12),
    r13 = const offset_of!(GuestRegisters, r13),
    r14 = const offset_of!(GuestRegisters, r14),
    r15 = const offset_of!(GuestRegisters, r15),
);
